INSERT INTO Competition (Name)
VALUES	 ('Cole, Wheeler and Wang'),
	 ('Moreno, Wallace and Brown'),
	 ('Morrison LLC'),
	 ('Vargas and Sons'),
	 ('Sanders-Sims'),
	 ('Griffin PLC'),
	 ('Scott PLC'),
	 ('Garcia-Taylor'),
	 ('Downs, Miranda and Martinez'),
	 ('Simpson, Baird and Jones'),
	 ('Kent-Holmes'),
	 ('Burgess-Brown'),
	 ('Wagner, Smith and Lee'),
	 ('Stanley Inc'),
	 ('Shepherd, Welch and Diaz'),
	 ('Brown Ltd'),
	 ('Gray LLC'),
	 ('Cohen-Robinson'),
	 ('Martin, Guerrero and Griffith'),
	 ('Anderson Ltd'),
	 ('Armstrong, Brock and Young'),
	 ('Robinson Inc'),
	 ('Gomez-Hughes'),
	 ('Montes, Chan and Mitchell'),
	 ('Brooks PLC'),
	 ('Collier, Lam and Love'),
	 ('Jones-Hernandez'),
	 ('Hodges, Kaufman and Ponce'),
	 ('Carpenter-Jones'),
	 ('Myers, Brewer and Davis'),
	 ('Walls-Obrien'),
	 ('Ray and Sons'),
	 ('Taylor-Medina'),
	 ('Espinoza-Lowe'),
	 ('Garcia and Sons'),
	 ('Clarke-Wilson'),
	 ('Turner-Wilson'),
	 ('Long and Sons'),
	 ('Lawrence, Miller and Hinton'),
	 ('Carter and Sons'),
	 ('Harper Ltd'),
	 ('Doyle-Aguilar'),
	 ('Martinez-Carter'),
	 ('Green, Carter and Hall'),
	 ('Thompson, Campbell and Brown'),
	 ('Sheppard, Bates and Zimmerman'),
	 ('Kirk, Rodriguez and Chang'),
	 ('Padilla PLC'),
	 ('Hall-Flores'),
	 ('Murphy, Thomas and Odonnell'),
	 ('Perez, Garcia and Brown'),
	 ('Marshall-Stark'),
	 ('Ramos, Mcintosh and Martin'),
	 ('Kelly, Joyce and Phelps'),
	 ('Bowman-Hughes'),
	 ('Scott-Murray'),
	 ('Acosta and Sons'),
	 ('Smith-Ortega'),
	 ('Hatfield-Thomas'),
	 ('Adams, Ramirez and White'),
	 ('Morgan PLC'),
	 ('Howell, Cunningham and Kelly'),
	 ('Gutierrez-Rodgers'),
	 ('Bowman Inc'),
	 ('Willis Ltd'),
	 ('Vaughn PLC'),
	 ('Mckee PLC'),
	 ('Todd-Aguilar'),
	 ('Hunter, Parker and Kane'),
	 ('Landry PLC'),
	 ('Cruz-Duffy'),
	 ('Freeman-Pratt'),
	 ('Gomez, Walker and Parker'),
	 ('Roberts Ltd'),
	 ('Johnson, Holmes and Espinoza'),
	 ('Evans-Nelson'),
	 ('Simmons-Spencer'),
	 ('Davidson, Spears and Aguilar'),
	 ('Marshall Inc'),
	 ('Ferrell LLC'),
	 ('Williams, Lewis and Davis'),
	 ('Padilla, Allen and Anderson'),
	 ('Hamilton PLC'),
	 ('Brown-Jones'),
	 ('Lee-Estrada'),
	 ('Green-Bishop'),
	 ('Spencer LLC'),
	 ('Smith and Sons'),
	 ('Trevino, Ward and Clark'),
	 ('Brown-Baker'),
	 ('Green-Lloyd'),
	 ('Graham-Love'),
	 ('Tucker, Gonzalez and Garcia'),
	 ('Hall-Edwards'),
	 ('Cameron, Moore and Cruz'),
	 ('Brown, Martinez and Pena'),
	 ('Rowland-Bowen'),
	 ('Davidson Group'),
	 ('Richards-Smith'),
	 ('Kelly, Mccullough and Castro'),
	 ('Wiley, Taylor and Brown'),
	 ('Holden, Stewart and Allen'),
	 ('Rosales-Kim'),
	 ('Daniel-Graham'),
	 ('Foster Inc'),
	 ('Salazar, Murphy and Avila'),
	 ('Johnson-Carr'),
	 ('Henderson-Lopez'),
	 ('Riley PLC'),
	 ('White, Wagner and Johnson'),
	 ('Robinson Inc'),
	 ('Hudson-Edwards'),
	 ('Thomas, Jensen and Price'),
	 ('Watson, Pham and Nichols'),
	 ('Perez LLC'),
	 ('Melendez-Harris'),
	 ('Santiago LLC'),
	 ('Coleman-Owens'),
	 ('Perez LLC'),
	 ('Jackson, Drake and Kirk'),
	 ('Johnson LLC'),
	 ('Clarke and Sons'),
	 ('Thompson, Palmer and Ortiz'),
	 ('Proctor, Richards and Buchanan'),
	 ('Lewis LLC'),
	 ('Diaz-Thomas'),
	 ('Cline, Holloway and Brown'),
	 ('Fernandez Ltd'),
	 ('Shaw LLC'),
	 ('Weaver, Gates and Day'),
	 ('Johnson and Sons'),
	 ('Jones, Gonzales and Ware'),
	 ('Ruiz LLC'),
	 ('Owens, Sweeney and Morgan'),
	 ('Andrade-Garcia'),
	 ('Harrison LLC'),
	 ('Lynch, Parrish and Drake'),
	 ('James Inc'),
	 ('Gay, Williams and Allen'),
	 ('Shaffer Group'),
	 ('Martin, Harris and Rivera'),
	 ('Turner, Austin and Conner'),
	 ('Tran Group'),
	 ('Holmes, Andrews and Friedman'),
	 ('Morris, White and Hickman'),
	 ('Douglas-Newton'),
	 ('Chapman-Wilcox'),
	 ('Brown-Woods'),
	 ('Elliott-Bishop'),
	 ('Mclaughlin Ltd'),
	 ('Castro and Sons'),
	 ('Lawrence-Schultz'),
	 ('Nichols-Hernandez'),
	 ('Wilson-Madden'),
	 ('Mercado PLC'),
	 ('Davis-Anderson'),
	 ('Key Group'),
	 ('Powell-Hicks'),
	 ('Harrison-Mendoza'),
	 ('Anderson, Norman and Williams'),
	 ('Lyons, Henry and Leon'),
	 ('Lopez PLC'),
	 ('Mack, Johnson and Greene'),
	 ('Young Group'),
	 ('Davis-Briggs'),
	 ('Miller, Alvarez and Phillips'),
	 ('Allen Inc'),
	 ('Novak, Taylor and Henson'),
	 ('Hoffman-Daniel'),
	 ('Holt PLC'),
	 ('Nielsen, Anderson and Ortiz'),
	 ('Rodriguez, Day and Shaw'),
	 ('Fry, Sanchez and Rodriguez'),
	 ('Newman, Reynolds and Santana'),
	 ('Walker, Sims and Gonzalez'),
	 ('Richardson, Williamson and Graham'),
	 ('Gallegos-Rhodes'),
	 ('Nguyen-Blair'),
	 ('Brown-Bush'),
	 ('Stevenson-Winters'),
	 ('Howell PLC'),
	 ('Anderson, Howard and Bell'),
	 ('Beard, Watts and Wood'),
	 ('Whitaker-Young'),
	 ('Carter-Nichols'),
	 ('Sutton-Eaton'),
	 ('Davis, White and Baldwin'),
	 ('Davis and Sons'),
	 ('Adams, Shields and Young'),
	 ('Lucas, Smith and Olsen'),
	 ('Walters-Johnson'),
	 ('Boyd Ltd'),
	 ('Jarvis-Huynh'),
	 ('Mcknight PLC'),
	 ('Carey, Horton and Reynolds'),
	 ('Wright Ltd'),
	 ('Obrien, Vargas and Pham'),
	 ('Hinton Ltd'),
	 ('Shah and Sons'),
	 ('Gonzalez LLC'),
	 ('Elliott-Adkins'),
	 ('Stevens Inc'),
	 ('Norton-Ortiz'),
	 ('Thompson-Perry'),
	 ('Riley-Salazar'),
	 ('Smith, Joseph and Miller'),
	 ('Fernandez, Hale and Davis'),
	 ('Guerrero-Romero'),
	 ('Compton, Morgan and Anderson'),
	 ('Cole, Mercer and Carter'),
	 ('Phillips-Chase'),
	 ('Guzman, Avila and Taylor'),
	 ('Banks Group'),
	 ('Nichols, Thompson and Horton'),
	 ('Sims, Miranda and Martinez'),
	 ('Stephens and Sons'),
	 ('Keith Inc'),
	 ('Petersen, Hamilton and Sims'),
	 ('Ramirez and Sons'),
	 ('Hensley-Long'),
	 ('Hampton Ltd'),
	 ('Holmes, Thomas and Hardy'),
	 ('Ruiz-Brown'),
	 ('Anderson, Solis and Spencer'),
	 ('Freeman, Vasquez and Barnes'),
	 ('Glover, Kennedy and Dean'),
	 ('Molina, Cox and Jenkins'),
	 ('Anderson, Lawson and Davis'),
	 ('Ballard-Roberson'),
	 ('Edwards-Mosley'),
	 ('Harrell-Huynh'),
	 ('Mcconnell PLC'),
	 ('Humphrey-Nunez'),
	 ('Lindsey LLC'),
	 ('Thomas, Dennis and Gray'),
	 ('Long LLC'),
	 ('Bell-Greene'),
	 ('Wolfe, Parker and Woodard'),
	 ('Sanchez-Coleman'),
	 ('Lee-Evans'),
	 ('Cruz, Perez and Randolph'),
	 ('Miller LLC'),
	 ('Salazar, Briggs and Carpenter'),
	 ('Cunningham-Perez'),
	 ('Solomon, Gilbert and Ho'),
	 ('Li, Schmitt and Gomez'),
	 ('Davis Group'),
	 ('Miller and Sons'),
	 ('Moore, Navarro and Lewis'),
	 ('Brown Group'),
	 ('Mcdonald-Brown'),
	 ('Thompson-Arnold'),
	 ('Smith-Nunez'),
	 ('Thomas Inc'),
	 ('Fisher, Rivas and Wang'),
	 ('Fritz LLC'),
	 ('Cross, Garcia and Weeks'),
	 ('Owen-Andrews'),
	 ('Carter-Jackson'),
	 ('Vargas-Flynn'),
	 ('Hawkins Ltd'),
	 ('Payne-Page'),
	 ('Nelson Group'),
	 ('Allen, Harris and Bender'),
	 ('Taylor LLC'),
	 ('Harris-Shea'),
	 ('Phillips Inc'),
	 ('Frank, Garner and Davis'),
	 ('Johnson, Herrera and White'),
	 ('Miller-Smith'),
	 ('Hernandez PLC'),
	 ('Stevens, Reilly and Carter'),
	 ('Campbell-Hunt'),
	 ('Anderson-Rodriguez'),
	 ('Wilson, Obrien and Thomas'),
	 ('Thompson, Campbell and Jenkins'),
	 ('Fernandez, Bell and Daniels'),
	 ('Harrington-Hall'),
	 ('Mason, Hayes and Hayes'),
	 ('Black, Rasmussen and Taylor'),
	 ('Shaw-Flores'),
	 ('Allen, Lang and Rodriguez'),
	 ('Brock, Sanders and Rasmussen'),
	 ('Smith, Scott and Davis'),
	 ('Morgan-Lara'),
	 ('Davis LLC'),
	 ('Becker-Rodriguez'),
	 ('Valenzuela-Rodriguez'),
	 ('Mcmahon-Brown'),
	 ('Hughes-Reyes'),
	 ('Dixon-Clarke'),
	 ('Russo-Andrade'),
	 ('Baker, Lynch and Aguilar'),
	 ('Robinson, Smith and Smith'),
	 ('Russell-Barnes'),
	 ('Brooks-Rivera'),
	 ('Moore PLC'),
	 ('Castro, Moreno and Baker'),
	 ('Hopkins-Morgan'),
	 ('Mayo-Rios'),
	 ('Kelly, Tran and Sanchez'),
	 ('Simmons Inc'),
	 ('Grant and Sons'),
	 ('Edwards, Davis and Fuller'),
	 ('Clark-Martin'),
	 ('Braun, Nguyen and Gibbs'),
	 ('Hill, Shelton and Bell'),
	 ('Barnes Ltd'),
	 ('Jackson, Ball and Lopez'),
	 ('Lambert, Farmer and Harrington'),
	 ('Villa-Hayes'),
	 ('Jones, Willis and Johnson'),
	 ('Bailey Ltd'),
	 ('Green, Hernandez and Williams'),
	 ('Collins PLC'),
	 ('Good, Ortiz and Brown'),
	 ('Rodriguez LLC'),
	 ('Mcguire-Rose'),
	 ('Valdez-Ramirez'),
	 ('Kelley, Vasquez and Trevino'),
	 ('Davis-Stewart'),
	 ('Moore PLC'),
	 ('Kim and Sons'),
	 ('Castillo, Johnson and Chavez'),
	 ('Mcpherson-Vasquez'),
	 ('Howard PLC'),
	 ('Williams-Bullock'),
	 ('Evans-Bernard'),
	 ('Quinn Group'),
	 ('Nolan-Swanson'),
	 ('Young, Walker and Henderson'),
	 ('Dominguez, Rodriguez and Holmes'),
	 ('Carey-Hart'),
	 ('Dixon, Evans and Williams'),
	 ('Harmon LLC'),
	 ('Tran, Moody and Lewis'),
	 ('Brown-Bowen'),
	 ('Walker LLC'),
	 ('Gordon LLC'),
	 ('Fox, Young and Jones'),
	 ('Johnson-Casey'),
	 ('Stone, Smith and Wolf'),
	 ('Solomon-Kirk'),
	 ('Pratt Group'),
	 ('Roberson LLC'),
	 ('Gonzales-Armstrong'),
	 ('Kelley, Diaz and Gonzalez'),
	 ('Watkins-Brady'),
	 ('Chandler and Sons'),
	 ('Johnson, Olson and Kim'),
	 ('Howard-Byrd'),
	 ('Hale-Sanchez'),
	 ('Russell, Fletcher and Fleming'),
	 ('Brewer Group'),
	 ('Becker-Glenn'),
	 ('Smith-Foster'),
	 ('Perez-Callahan'),
	 ('Clayton, Berry and Tate'),
	 ('Martinez Inc'),
	 ('Owens-Johnson'),
	 ('Brown-Marquez'),
	 ('Hale, Brooks and Price'),
	 ('Moore, Cantu and Hudson'),
	 ('Rodriguez-Buchanan'),
	 ('White, Williams and Myers'),
	 ('Fowler, Scott and Casey'),
	 ('Green-Martinez'),
	 ('Oliver Group'),
	 ('Payne Inc'),
	 ('Dennis and Sons'),
	 ('Patrick-Jones'),
	 ('Richardson-Gutierrez'),
	 ('Garcia-Mitchell'),
	 ('Nelson, Smith and Jones'),
	 ('Powers LLC'),
	 ('Martinez, Thornton and Jacobs'),
	 ('Erickson PLC'),
	 ('Jones, Martinez and Clark'),
	 ('Wood and Sons'),
	 ('Burns-Lee'),
	 ('Jones-Russell'),
	 ('Bowman LLC'),
	 ('Whitehead-Alvarado'),
	 ('Peterson-Todd'),
	 ('Hensley Group'),
	 ('Mitchell, Ramirez and Glover'),
	 ('Crawford-Hill'),
	 ('Baker-Huerta'),
	 ('Clark, Mueller and Benjamin'),
	 ('Alvarado-Marquez'),
	 ('Gardner, Smith and Sherman'),
	 ('Long, Perez and Bender'),
	 ('Schmidt-Schmidt'),
	 ('Wolf PLC'),
	 ('Cox, Martin and Wright'),
	 ('Bowers, Dorsey and Murphy'),
	 ('Russell Group'),
	 ('Bradley-Henry'),
	 ('Scott PLC'),
	 ('Nielsen, Brown and Jones'),
	 ('Rivera-Bowen'),
	 ('Houston-Martin'),
	 ('Schultz LLC'),
	 ('Anderson, Lawson and Harrison'),
	 ('Sanford-Tran'),
	 ('Harrison PLC'),
	 ('Tyler-Hill'),
	 ('Hubbard, Schneider and Garcia'),
	 ('Wu, Howell and Williams'),
	 ('Perry, Johnson and Jones'),
	 ('Schneider, Anderson and Dixon'),
	 ('Davis-Johnson'),
	 ('Booth Ltd'),
	 ('Campbell Ltd'),
	 ('Brown-Tate'),
	 ('Rivers LLC'),
	 ('Baldwin-Robinson'),
	 ('Novak, Soto and Cunningham'),
	 ('Price, Howard and Butler'),
	 ('Robertson, Walker and Greene'),
	 ('Malone, Sanchez and Rogers'),
	 ('Rose and Sons'),
	 ('Miles PLC'),
	 ('Anderson-Houston'),
	 ('Bennett Group'),
	 ('Hampton, Guzman and Henderson'),
	 ('Martinez-Johnson'),
	 ('Davila-Brooks'),
	 ('Stevenson and Sons'),
	 ('Lee Group'),
	 ('Pugh and Sons'),
	 ('Powers and Sons'),
	 ('Myers, Campos and Madden'),
	 ('Griffin, Hudson and Evans'),
	 ('Acevedo Group'),
	 ('George, Simpson and Mosley'),
	 ('Berry Ltd'),
	 ('Cummings, Johnson and Salazar'),
	 ('Mata, Cooper and Garcia'),
	 ('Williams, Smith and Williams'),
	 ('Hebert Inc'),
	 ('Butler, Henderson and White'),
	 ('Williams Ltd'),
	 ('Wilson and Sons'),
	 ('Armstrong, Chambers and Goodman'),
	 ('Griffin Inc'),
	 ('Perry-Collins'),
	 ('Rhodes Ltd'),
	 ('Walter, Thompson and Moore'),
	 ('Brown-Chang'),
	 ('Espinoza-Aguilar'),
	 ('Pratt Group'),
	 ('Brown PLC'),
	 ('Ruiz-Nelson'),
	 ('Kramer, Powell and Hunter'),
	 ('Reed, Bender and Good'),
	 ('Ball, Velez and Ray'),
	 ('Williams-Lewis'),
	 ('Stevens and Sons'),
	 ('Medina-Harrison'),
	 ('Faulkner, Thompson and Romero'),
	 ('Delgado LLC'),
	 ('Vasquez Inc'),
	 ('Mack, Moore and Gross'),
	 ('Murphy-Robbins'),
	 ('Rubio, Hamilton and Walker'),
	 ('Blankenship-Jacobs'),
	 ('Peterson-Ryan'),
	 ('Patrick-Carpenter'),
	 ('Lambert-Gardner'),
	 ('Brown-Ruiz'),
	 ('Howard Ltd'),
	 ('Harris Ltd'),
	 ('Terrell Ltd'),
	 ('Khan Inc'),
	 ('Summers, Fleming and Phillips'),
	 ('Payne, White and Perez'),
	 ('Ortiz, Whitehead and Cunningham'),
	 ('Henderson, Bradley and Smith'),
	 ('Glass-Gonzalez'),
	 ('Scott LLC'),
	 ('Stein Inc'),
	 ('Mitchell, Bullock and Harrison'),
	 ('Allen-Todd'),
	 ('Martin-Thomas'),
	 ('Rich LLC'),
	 ('Gould, Contreras and Black'),
	 ('Jordan-Barnett'),
	 ('Mclaughlin-Martin'),
	 ('Miller-Meyer'),
	 ('Fisher Ltd'),
	 ('Guerrero-Patel'),
	 ('Alvarado, Miles and Montoya'),
	 ('Morris-Brown'),
	 ('Carroll-Anderson'),
	 ('Nelson Ltd'),
	 ('Anthony-Stewart'),
	 ('Wolfe Ltd'),
	 ('Levine-Delgado'),
	 ('Johnson, Davidson and Gray');
