SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO Competition (Name)
VALUES	 ('Johnson PLC'),
	 ('Elliott LLC'),
	 ('Hunter-Wallace'),
	 ('Dyer Inc'),
	 ('Roman, Jones and Middleton'),
	 ('Stewart-Robertson'),
	 ('Church-Parker'),
	 ('Phillips and Sons'),
	 ('Smith-Chavez'),
	 ('Young, Allen and Robinson'),
	 ('Powers and Sons'),
	 ('Hammond, Harvey and Key'),
	 ('Williams-Dean'),
	 ('Ramirez and Sons'),
	 ('Sullivan-May'),
	 ('Adkins and Sons'),
	 ('Stone-Rowe'),
	 ('Young, Nicholson and Wagner'),
	 ('Crawford-Morales'),
	 ('Smith, Gonzalez and Gonzalez'),
	 ('Rodriguez PLC'),
	 ('Moore-Porter'),
	 ('Donovan PLC'),
	 ('Newman, Johnson and Freeman'),
	 ('Arroyo-Griffith'),
	 ('Vazquez, Wright and Villanueva'),
	 ('Simmons LLC'),
	 ('Huber, Sawyer and Davis'),
	 ('Newton, Nichols and Henderson'),
	 ('Cox-Monroe'),
	 ('Shaw, Valencia and Burke'),
	 ('Olson and Sons'),
	 ('Kim, Owens and Maxwell'),
	 ('Smith PLC'),
	 ('Sanchez, Mcfarland and Jackson'),
	 ('Greer, Decker and Keller'),
	 ('Rose, Walker and Hester'),
	 ('Sanders, Price and Munoz'),
	 ('Bowen-Soto'),
	 ('Lee Ltd'),
	 ('Alvarado, Walker and Stephenson'),
	 ('Navarro, Clay and Davis'),
	 ('Fields LLC'),
	 ('Woods Inc'),
	 ('Allen-Bennett'),
	 ('Strong, Rich and Jones'),
	 ('Crawford-Robinson'),
	 ('Smith, Cox and Parrish'),
	 ('Harvey-Gutierrez'),
	 ('Jackson-Vasquez'),
	 ('Fox-Stone'),
	 ('Dawson, Smith and Page'),
	 ('Brandt Group'),
	 ('Parker-Ponce'),
	 ('Perez, Anderson and Peters'),
	 ('Cox, Martin and Garcia'),
	 ('Watkins-Williams'),
	 ('Mcdonald Inc'),
	 ('Taylor PLC'),
	 ('Gallagher, Perry and Jordan'),
	 ('Mitchell, Jacobs and Powell'),
	 ('Wilson LLC'),
	 ('Kennedy, Gonzalez and Walton'),
	 ('Carter LLC'),
	 ('Adams, Martinez and Ellis'),
	 ('Velasquez, Chen and Garcia'),
	 ('Mccoy, Edwards and English'),
	 ('Moore-Price'),
	 ('Marshall, Reed and Haynes'),
	 ('Palmer, Powell and Douglas'),
	 ('Martinez Group'),
	 ('Figueroa-Newman'),
	 ('Johnson-Macdonald'),
	 ('Meyer, Ray and Hudson'),
	 ('Ramirez, Hunter and Zimmerman'),
	 ('Robinson, Richmond and Johnson'),
	 ('King, Garcia and Sullivan'),
	 ('Anderson and Sons'),
	 ('Jackson-Elliott'),
	 ('Barnes-Lee'),
	 ('Johnson Ltd'),
	 ('Raymond, Johns and Gonzalez'),
	 ('Bailey-Johnson'),
	 ('Lang LLC'),
	 ('Vincent Group'),
	 ('Miller Ltd'),
	 ('Ayers, Hansen and Crosby'),
	 ('Castro, Wheeler and Martinez'),
	 ('Hoffman, Smith and Garcia'),
	 ('Long, Singleton and Decker'),
	 ('Long-Hernandez'),
	 ('Mcintosh, Jones and Taylor'),
	 ('West, Anderson and Gilbert'),
	 ('Moore Ltd'),
	 ('Vang Group'),
	 ('Myers-Wood'),
	 ('Diaz and Sons'),
	 ('Graves-Ballard'),
	 ('Miller-Meyer'),
	 ('Barton, Sloan and Henderson'),
	 ('Howard, Guerrero and Williams'),
	 ('Morris Group'),
	 ('Palmer-Pitts'),
	 ('Palmer-Tran'),
	 ('Phillips-Clark'),
	 ('Dixon, Moran and Garcia'),
	 ('Rodriguez, Fry and Richards'),
	 ('Dennis, Barr and Smith'),
	 ('Evans, Richardson and Martin'),
	 ('Johnson, Willis and Butler'),
	 ('Hoffman Inc'),
	 ('Buck-Baldwin'),
	 ('Acosta LLC'),
	 ('Salinas Inc'),
	 ('Wilcox-Cantu'),
	 ('Jacobson-Dillon'),
	 ('Smith, Sanders and Anderson'),
	 ('Ferguson-Terry'),
	 ('Alexander Group'),
	 ('Thomas, Cabrera and Lopez'),
	 ('Lopez-Ellison'),
	 ('Martinez PLC'),
	 ('Stevens Ltd'),
	 ('Williams and Sons'),
	 ('Jennings, Andrews and Madden'),
	 ('Oconnell, Bowers and Perry'),
	 ('Mercado Ltd'),
	 ('Russell LLC'),
	 ('Mendoza Ltd'),
	 ('Fitzgerald, Welch and Chan'),
	 ('Gomez, Crawford and Hudson'),
	 ('Nguyen, Gonzalez and Miller'),
	 ('Williams, Moore and Martinez'),
	 ('Martin-Henry'),
	 ('Pearson, Branch and Jefferson'),
	 ('Williams, Ross and White'),
	 ('Hawkins Ltd'),
	 ('Baker and Sons'),
	 ('Boyer, Johnson and Warren'),
	 ('Myers-Sherman'),
	 ('Taylor LLC'),
	 ('Jenkins-Howard'),
	 ('Walker, Dawson and Edwards'),
	 ('Nunez and Sons'),
	 ('Porter, Hebert and Miller'),
	 ('Johnson LLC'),
	 ('Daniels, White and Murray'),
	 ('Kramer-Cobb'),
	 ('Campbell, Riley and Garcia'),
	 ('Johnson-Jackson'),
	 ('Ball-Frederick'),
	 ('Alexander, Smith and Hill'),
	 ('Greene-Salazar'),
	 ('Figueroa-Jacobs'),
	 ('Olson-Harrell'),
	 ('Anderson, Bolton and Banks'),
	 ('Walters Group'),
	 ('Valentine LLC'),
	 ('James, Sanchez and Bruce'),
	 ('Foster, Swanson and Johnson'),
	 ('Herring Ltd'),
	 ('Nelson PLC'),
	 ('Clark PLC'),
	 ('Mckay-Wolf'),
	 ('Miller LLC'),
	 ('Miller, Gallegos and Wilson'),
	 ('Zuniga-Carr'),
	 ('Robinson, Tucker and Woodard'),
	 ('Martinez, Davis and Riley'),
	 ('Duffy-Rodriguez'),
	 ('Jacobs LLC'),
	 ('Solis Group'),
	 ('Haynes, Fisher and Harrison'),
	 ('Wagner-Swanson'),
	 ('Mann, Hudson and Roth'),
	 ('Rodriguez LLC'),
	 ('Thompson, Taylor and Marshall'),
	 ('Lopez-Rodriguez'),
	 ('Lee-Stark'),
	 ('Tucker-Castaneda'),
	 ('Nguyen LLC'),
	 ('Caldwell-Stokes'),
	 ('Garcia-Camacho'),
	 ('Jones, Harrison and Gray'),
	 ('Cruz Inc'),
	 ('Hernandez LLC'),
	 ('Shaw PLC'),
	 ('Frey-Everett'),
	 ('Blankenship Inc'),
	 ('Mann-Smith'),
	 ('Morrison, Gonzales and White'),
	 ('Morgan Inc'),
	 ('Nelson, Fisher and Robertson'),
	 ('Davis Group'),
	 ('Powers, Arnold and Maldonado'),
	 ('Jackson, Summers and Ewing'),
	 ('Castro, Ortiz and Holland'),
	 ('Walker-Campbell'),
	 ('Duffy, King and Stanton'),
	 ('Moran Ltd'),
	 ('Munoz-Camacho'),
	 ('Long, Hernandez and Payne'),
	 ('Escobar Ltd'),
	 ('Wilson PLC'),
	 ('Robertson Inc'),
	 ('Cabrera-Russell'),
	 ('Rose, Smith and Williams'),
	 ('Donovan, Anderson and Johns'),
	 ('Pennington-Scott'),
	 ('Adams, Holland and Stokes'),
	 ('Fisher-Evans'),
	 ('Rollins-Torres'),
	 ('Cook, Weiss and Stewart'),
	 ('Lam, Roberts and Walter'),
	 ('Gibbs-Brown'),
	 ('Hernandez-Nelson'),
	 ('Richards-Patel'),
	 ('Rodriguez-Nguyen'),
	 ('Miller, Carr and Reid'),
	 ('Tucker, Moore and Carney'),
	 ('George-Kim'),
	 ('Blanchard-Wilson'),
	 ('Gilmore, Strickland and Hernandez'),
	 ('Mayo Group'),
	 ('Garcia-Gill'),
	 ('Adams, Anderson and Walker'),
	 ('Lee Ltd'),
	 ('Rowe, Rodgers and Wilson'),
	 ('Davis-Maldonado'),
	 ('Ryan Group'),
	 ('Hoover-Espinoza'),
	 ('Brown, Case and Nelson'),
	 ('Terry-Benson'),
	 ('Jackson PLC'),
	 ('Oconnor, Reid and Cox'),
	 ('Martin Group'),
	 ('English-Ward'),
	 ('Adams, Robinson and Barrett'),
	 ('Ayala Ltd'),
	 ('Reynolds, Mitchell and Ray'),
	 ('Oliver, Duran and Padilla'),
	 ('Powell Group'),
	 ('Johnson and Sons'),
	 ('Carter Ltd'),
	 ('Johnson-Odom'),
	 ('Jones-Fischer'),
	 ('Roberts, Lowe and Rivas'),
	 ('Gutierrez Group'),
	 ('Higgins, Butler and Jennings'),
	 ('Dawson, Brady and Rivera'),
	 ('Smith-Mendez'),
	 ('Anderson PLC'),
	 ('Davenport Inc'),
	 ('Cook, Harris and Hancock'),
	 ('Williams, Walker and Phillips'),
	 ('Hogan Inc'),
	 ('Gray and Sons'),
	 ('Powell Group'),
	 ('Anderson-Hernandez'),
	 ('Gardner, Cruz and Chavez'),
	 ('Phillips Group'),
	 ('Bryant-Krueger'),
	 ('Charles, Beasley and Moore'),
	 ('Sweeney Ltd'),
	 ('Brown, Brooks and Ayala'),
	 ('Vance Inc'),
	 ('Kelly Group'),
	 ('Vincent PLC'),
	 ('Blackwell, Parker and Douglas'),
	 ('Zimmerman Inc'),
	 ('Wilkinson Ltd'),
	 ('Bullock PLC'),
	 ('Smith, George and Johnson'),
	 ('Patel-Farmer'),
	 ('Morgan Group'),
	 ('Perez and Sons'),
	 ('Roberts PLC'),
	 ('Walter and Sons'),
	 ('Mann-Armstrong'),
	 ('Keller Ltd'),
	 ('Collins Inc'),
	 ('Johnson, Parks and Armstrong'),
	 ('Williams-Bennett'),
	 ('Stewart PLC'),
	 ('Cox, Long and Stewart'),
	 ('May-Wilson'),
	 ('Jones LLC'),
	 ('Watkins-Brown'),
	 ('Taylor LLC'),
	 ('Clark, Ferrell and Glenn'),
	 ('Sullivan-Waters'),
	 ('Thompson Inc'),
	 ('Walsh Inc'),
	 ('Christian-Reyes'),
	 ('Smith Ltd'),
	 ('Jarvis PLC'),
	 ('Cummings, Reeves and Schroeder'),
	 ('Woods-Ford'),
	 ('Norton-Cruz'),
	 ('Cameron-Crane'),
	 ('Rodriguez-Trevino'),
	 ('Silva-Anthony'),
	 ('Sawyer Group'),
	 ('Weaver-Cook'),
	 ('Fox Ltd'),
	 ('Meza, Butler and Jones'),
	 ('Roberts, Ruiz and Roth'),
	 ('Perry LLC'),
	 ('Cannon-Brown'),
	 ('Nelson-Manning'),
	 ('Stout, Guerrero and Clark'),
	 ('Colon Group'),
	 ('Villa, Dean and Gray'),
	 ('Baker LLC'),
	 ('Shepherd, Simpson and Flores'),
	 ('Spencer PLC'),
	 ('Richard, Gardner and Salazar'),
	 ('Smith, Brown and Price'),
	 ('Cross, Conrad and Cummings'),
	 ('Jennings-Clark'),
	 ('Scott, Mann and Fox'),
	 ('Stephens, Clark and Hall'),
	 ('Kennedy-Bailey'),
	 ('Roth-Walters'),
	 ('Holt, Wagner and Hayes'),
	 ('Wells Group'),
	 ('Morris Inc'),
	 ('Cox, Martin and Moss'),
	 ('Vazquez Ltd'),
	 ('Johnson LLC'),
	 ('Braun Inc'),
	 ('Wallace-Davis'),
	 ('Ibarra, Martin and Cooper'),
	 ('Davis, Jackson and Barrett'),
	 ('Mann Inc'),
	 ('Barajas and Sons'),
	 ('Wilson-Adams'),
	 ('Owen, Gutierrez and Davis'),
	 ('Nichols, Wilson and Cochran'),
	 ('Alvarez-Gilmore'),
	 ('Schmitt, Day and Murphy'),
	 ('Cochran, Lee and Thompson'),
	 ('Cohen, Brown and Diaz'),
	 ('West, Welch and Neal'),
	 ('Bowers-Brown'),
	 ('Smith, Nelson and Mcguire'),
	 ('Perez, Waters and Murray'),
	 ('Lynch Group'),
	 ('Miller Inc'),
	 ('Bell, Chandler and Rivera'),
	 ('Cobb, Shields and Baker'),
	 ('Ross and Sons'),
	 ('Martinez Group'),
	 ('Richardson and Sons'),
	 ('Chapman-Simmons'),
	 ('Williams-Bridges'),
	 ('Hogan, Meyer and Stout'),
	 ('Hudson Group'),
	 ('Johnson Inc'),
	 ('Williams, Vargas and Beck'),
	 ('Romero Group'),
	 ('Turner, Jackson and Mccullough'),
	 ('Hernandez, Wilson and Salazar'),
	 ('Thomas, Lee and Thompson'),
	 ('Mcbride-Mitchell'),
	 ('Davis-Morris'),
	 ('Ross, Rodriguez and Perkins'),
	 ('Scott LLC'),
	 ('Carroll-Grant'),
	 ('Valencia, Anderson and Jarvis'),
	 ('Walker, Tucker and Beasley'),
	 ('Thompson Ltd'),
	 ('Bryant, Rios and Lane'),
	 ('Roman, Davis and Stephens'),
	 ('Baker, Bonilla and Taylor'),
	 ('Weiss-Vargas'),
	 ('Lynn, Williams and Griffin'),
	 ('Pacheco-Garza'),
	 ('Miller-Williams'),
	 ('Gutierrez, Floyd and Mathews'),
	 ('Fox, Coleman and Carson'),
	 ('Hamilton Inc'),
	 ('Gallagher LLC'),
	 ('Gordon Ltd'),
	 ('Daniels, Miller and Hudson'),
	 ('Davis-Velazquez'),
	 ('Goodwin Ltd'),
	 ('Gomez-Vaughan'),
	 ('Smith Ltd'),
	 ('Melton-Obrien'),
	 ('Cochran-Benson'),
	 ('Reed-Moss'),
	 ('Sanchez, Murray and Hancock'),
	 ('Jackson, Davis and West'),
	 ('Long, Hamilton and Ward'),
	 ('Adams, Dougherty and Harris'),
	 ('Davis PLC'),
	 ('Gilbert, Johnson and Perez'),
	 ('Thompson Ltd'),
	 ('Turner Group'),
	 ('Valencia-Gonzales'),
	 ('Garcia Inc'),
	 ('Sellers, Lloyd and Marks'),
	 ('Morris LLC'),
	 ('Gardner Ltd'),
	 ('Olson-Turner'),
	 ('Franklin-Goodman'),
	 ('Hull-Wilson'),
	 ('Thompson-Clark'),
	 ('Haney, Kent and Miller'),
	 ('Nguyen, Duncan and Rivera'),
	 ('Mendoza, Rosales and Mccall'),
	 ('Hamilton-Foster'),
	 ('Jacobs, Carter and Armstrong'),
	 ('Marquez, King and Diaz'),
	 ('Schmidt-Perez'),
	 ('Christensen Inc'),
	 ('Jacobson, Cook and George'),
	 ('Hamilton-Newman'),
	 ('Jackson and Sons'),
	 ('Estrada, Wallace and Gamble'),
	 ('Schmidt, Palmer and Love'),
	 ('Garcia, Hansen and Howell'),
	 ('Martinez, Buckley and Carrillo'),
	 ('Rivas-Roy'),
	 ('Alvarez, Walters and Lopez'),
	 ('Gonzalez, Harmon and Stanley'),
	 ('Miller, Hanson and Owens'),
	 ('Carson-Drake'),
	 ('Farmer-Bautista'),
	 ('Hunter PLC'),
	 ('Boyer Group'),
	 ('Simpson, Moore and Anderson'),
	 ('Yoder, Snow and Alexander'),
	 ('Grimes Inc'),
	 ('Harris-Briggs'),
	 ('Fisher Inc'),
	 ('Mckinney Inc'),
	 ('Santiago Group'),
	 ('Reyes, Hopkins and Barker'),
	 ('Hill-Bond'),
	 ('Lawson, Callahan and Johnson'),
	 ('Ward Inc'),
	 ('Thomas Group'),
	 ('Rice-Nelson'),
	 ('Evans-Cobb'),
	 ('Wagner and Sons'),
	 ('Schultz-Gutierrez'),
	 ('Smith PLC'),
	 ('Choi, Lopez and Gamble'),
	 ('Johnson LLC'),
	 ('Watkins Inc'),
	 ('Richardson Group'),
	 ('Brooks LLC'),
	 ('Austin, Gonzalez and Sullivan'),
	 ('Hughes Group'),
	 ('Wells-Thornton'),
	 ('Stevens, Robinson and Torres'),
	 ('Lowe-Harris'),
	 ('Salazar PLC'),
	 ('Hernandez, Barker and Kelley'),
	 ('Russo Inc'),
	 ('Hebert, Jones and Hicks'),
	 ('Hudson, Chan and Wheeler'),
	 ('Hernandez Ltd'),
	 ('Garrison LLC'),
	 ('Berry, Watts and West'),
	 ('Dixon-Clark'),
	 ('Mcneil-Morris'),
	 ('James, Mata and Blackwell'),
	 ('Smith, Wright and Jones'),
	 ('Melton LLC'),
	 ('Brewer, Hardin and Christensen'),
	 ('Barnes, Owen and Clarke'),
	 ('Brown-Mercer'),
	 ('Watson, White and Smith'),
	 ('Ward, Ellis and Daniels'),
	 ('Lucas, Phillips and Ford'),
	 ('Bennett and Sons'),
	 ('Schultz PLC'),
	 ('Herring-Miller'),
	 ('Williams, Harris and Hooper'),
	 ('Alvarado, Schmidt and Thompson'),
	 ('Schroeder, Turner and Spence'),
	 ('Jackson-Johnson'),
	 ('Rodriguez, Hull and Schwartz'),
	 ('Thomas-Brooks'),
	 ('Miller Ltd'),
	 ('Mason-Macdonald'),
	 ('Wheeler PLC'),
	 ('Mack, Obrien and Watkins'),
	 ('Martinez, Hamilton and White'),
	 ('Erickson-Roy'),
	 ('Martinez, Carter and Edwards'),
	 ('Roberts Group'),
	 ('Williams LLC'),
	 ('Johnson, Howe and Barker'),
	 ('Newman-Fernandez'),
	 ('Gray-Patel'),
	 ('Haynes Group');
SET FOREIGN_KEY_CHECKS = 1;