INSERT INTO Competition (Name)
VALUES	 ('James-Mccoy'),
	 ('Robinson, Ingram and Romero'),
	 ('Lee-Cooper'),
	 ('Mclean-Allen'),
	 ('Warren, Ramos and Duffy'),
	 ('Gonzalez, Perez and Smith'),
	 ('Pearson, Porter and Reed'),
	 ('Alexander-Richardson'),
	 ('Payne PLC'),
	 ('Freeman, Farley and Frey'),
	 ('Fitzpatrick PLC'),
	 ('Fields-Howard'),
	 ('Lee PLC'),
	 ('Anderson-Sims'),
	 ('Montgomery-Smith'),
	 ('Meyer Group'),
	 ('Smith, Huffman and Stout'),
	 ('Smith Ltd'),
	 ('Mosley, Curry and Olson'),
	 ('Wilson-Brown'),
	 ('Dunn and Sons'),
	 ('Dominguez Inc'),
	 ('Harris-Gonzalez'),
	 ('Ellis-Mcdonald'),
	 ('Robinson, Velasquez and Contreras'),
	 ('Brooks-Wright'),
	 ('Johnson, Flowers and Robles'),
	 ('Warren PLC'),
	 ('Hale-Johnson'),
	 ('Morgan, Davis and Bean'),
	 ('Cox-Lynn'),
	 ('Sparks-Taylor'),
	 ('Mclean-Crane'),
	 ('Villarreal-Macdonald'),
	 ('Hall-Sutton'),
	 ('Briggs Group'),
	 ('Mccarty, Harrison and Hernandez'),
	 ('Barrett, Atkinson and Thompson'),
	 ('Singleton-Poole'),
	 ('Jackson-York'),
	 ('Wolf, Lee and Maynard'),
	 ('Young, Spears and Stuart'),
	 ('King-Owens'),
	 ('Williams-Phillips'),
	 ('Fischer PLC'),
	 ('Rodriguez-Villanueva'),
	 ('Mccarty-Castro'),
	 ('Livingston Ltd'),
	 ('Preston, Dawson and Anderson'),
	 ('Davis, Valencia and Lee'),
	 ('Thompson and Sons'),
	 ('Price, Wilson and Hernandez'),
	 ('Wilson, Shaw and Patterson'),
	 ('Estes and Sons'),
	 ('Ramirez-Clay'),
	 ('Coleman Group'),
	 ('Lester Ltd'),
	 ('Douglas, Orozco and Diaz'),
	 ('Howard-Torres'),
	 ('Mckinney, Williams and Mosley'),
	 ('Jones, Lopez and Morales'),
	 ('Scott PLC'),
	 ('Howard Ltd'),
	 ('Kane Ltd'),
	 ('Page and Sons'),
	 ('Carpenter Inc'),
	 ('Martinez-Melendez'),
	 ('Thomas-Williams'),
	 ('Reid-Gomez'),
	 ('Graham, Baldwin and Goodwin'),
	 ('Johnson, Pena and Jones'),
	 ('Gutierrez, Campbell and Allen'),
	 ('Benson and Sons'),
	 ('Jackson-Higgins'),
	 ('Martinez and Sons'),
	 ('Harrison-Carr'),
	 ('Jones PLC'),
	 ('Diaz-Murray'),
	 ('Bean-Walters'),
	 ('Coleman, Miller and Marsh'),
	 ('Huffman-Martin'),
	 ('Clark, Hall and Gilmore'),
	 ('Armstrong-Newman'),
	 ('Williams, Lee and Morgan'),
	 ('Wagner, Cruz and Cordova'),
	 ('Sanders-Garza'),
	 ('Jacobson-Martinez'),
	 ('Morris Ltd'),
	 ('Miller Inc'),
	 ('Velasquez-Solis'),
	 ('Lam LLC'),
	 ('Miller LLC'),
	 ('Carter-Jones'),
	 ('Hart and Sons'),
	 ('Roberts Group'),
	 ('Johnson Group'),
	 ('Wong, Weaver and Perez'),
	 ('Russo, Woods and Walker'),
	 ('Evans Group'),
	 ('Hayes-Turner'),
	 ('Martin-Carter'),
	 ('Greene PLC'),
	 ('Neal-Michael'),
	 ('Snyder PLC'),
	 ('Young PLC'),
	 ('Johnson, Hayden and Schroeder'),
	 ('Jones, Burns and Rodriguez'),
	 ('Rivera Ltd'),
	 ('Sexton, Hunter and Green'),
	 ('Waller-Scott'),
	 ('Kelley Inc'),
	 ('Turner-Briggs'),
	 ('Rogers and Sons'),
	 ('Ford-Spence'),
	 ('Guerrero-Cooper'),
	 ('Mckay LLC'),
	 ('Perry, Gardner and Sanchez'),
	 ('Russell-Clayton'),
	 ('Ayala LLC'),
	 ('Robinson, Long and Holt'),
	 ('Wise-Barnes'),
	 ('Pearson, Martin and Chen'),
	 ('Thomas, Campbell and Gallegos'),
	 ('Cruz, Lopez and Davis'),
	 ('Holt and Sons'),
	 ('Davila Group'),
	 ('Stevenson LLC'),
	 ('George, Ryan and Williams'),
	 ('Holmes, Martinez and Kline'),
	 ('Dillon, Baxter and Smith'),
	 ('Smith, Avila and Miller'),
	 ('Reed-Munoz'),
	 ('James-Morrow'),
	 ('Reed Inc'),
	 ('Huang Ltd'),
	 ('Allen, Rocha and Conway'),
	 ('Davis Ltd'),
	 ('Ward LLC'),
	 ('Casey-Hanson'),
	 ('Lee, Gray and Morton'),
	 ('Campos, Hayes and Munoz'),
	 ('Vargas, Morris and Turner'),
	 ('Barrett Group'),
	 ('Newman Group'),
	 ('White-Mendez'),
	 ('Berg, Boone and Horn'),
	 ('Johnson-Fleming'),
	 ('Rice, Caldwell and Johnson'),
	 ('Avila-Ryan'),
	 ('Taylor Group'),
	 ('Buck-Chapman'),
	 ('Rodriguez-Hernandez'),
	 ('Larson-Scott'),
	 ('Johnston Group'),
	 ('Peterson, Bean and Hines'),
	 ('Sosa, Alvarado and Moyer'),
	 ('Weaver, Baldwin and Bell'),
	 ('Davis-Taylor'),
	 ('Harris-Thomas'),
	 ('Lewis-Cooper'),
	 ('Zimmerman Ltd'),
	 ('White, Spencer and Chandler'),
	 ('Warren-Torres'),
	 ('Thompson-Jensen'),
	 ('Petty-Campos'),
	 ('Daniel, Baker and Powers'),
	 ('Barnes, Gates and Reed'),
	 ('Davis, Jackson and Nichols'),
	 ('Reed-Haynes'),
	 ('Alvarez LLC'),
	 ('Carter-Banks'),
	 ('Holland-Steele'),
	 ('Hernandez, Doyle and Jones'),
	 ('Diaz-Young'),
	 ('Benton, Hall and Moss'),
	 ('Reynolds Inc'),
	 ('Patton Inc'),
	 ('Newton, Arnold and Melendez'),
	 ('Luna, Harrison and Barnes'),
	 ('Wilson PLC'),
	 ('Rivera PLC'),
	 ('Smith, Hudson and Mclean'),
	 ('Doyle-Bridges'),
	 ('Jensen, Padilla and Williams'),
	 ('Montgomery Group'),
	 ('Owen-Meza'),
	 ('Woods, Jones and Lucero'),
	 ('Freeman, Werner and Harris'),
	 ('Green, West and Brooks'),
	 ('Hughes PLC'),
	 ('Nelson Inc'),
	 ('Brooks Group'),
	 ('Doyle-Arias'),
	 ('Parrish-Boone'),
	 ('Guerrero, Riggs and Jensen'),
	 ('Howell, Thomas and Rodriguez'),
	 ('Diaz, Sanchez and Watkins'),
	 ('Vazquez Inc'),
	 ('Taylor and Sons'),
	 ('Houston, Garcia and Mendoza'),
	 ('Whitehead Group'),
	 ('Escobar-Garcia'),
	 ('Fletcher-Woods'),
	 ('Harrison, Reeves and Shelton'),
	 ('Mills-Collins'),
	 ('Harris-Arnold'),
	 ('Carey-Ellis'),
	 ('Frost-Spencer'),
	 ('Gordon LLC'),
	 ('Clark-Kelley'),
	 ('Carroll Ltd'),
	 ('May-Carter'),
	 ('Hall, Stewart and Martinez'),
	 ('Moore-Gilbert'),
	 ('Collins, Powell and Page'),
	 ('Fisher-Gay'),
	 ('King-Austin'),
	 ('Brown Ltd'),
	 ('Jones, Wright and Benson'),
	 ('Taylor-Brown'),
	 ('Wells Group'),
	 ('Lopez-Grant'),
	 ('Powell, Maxwell and Gonzalez'),
	 ('Hood Group'),
	 ('Estrada Inc'),
	 ('Martinez, Sutton and Foster'),
	 ('Woods Inc'),
	 ('Holmes-Bradley'),
	 ('Irwin LLC'),
	 ('Ward, Li and Clark'),
	 ('Bennett Group'),
	 ('Miller, Black and Gonzalez'),
	 ('Johnson Ltd'),
	 ('Vargas-Stone'),
	 ('Rodriguez-Anderson'),
	 ('Gonzalez Group'),
	 ('Smith-Bailey'),
	 ('Johnson-Mcguire'),
	 ('Ponce, Kemp and Lopez'),
	 ('Rogers-Bailey'),
	 ('Brown-Melton'),
	 ('Cervantes, Webster and Cook'),
	 ('Pearson LLC'),
	 ('Jones LLC'),
	 ('Smith, Blair and Walter'),
	 ('Bell Ltd'),
	 ('Vargas, Moore and Mcneil'),
	 ('Reed, Beck and Chase'),
	 ('Hernandez-Rodriguez'),
	 ('Orozco Inc'),
	 ('Tate, Robinson and Williamson'),
	 ('Clark Inc'),
	 ('Miller-Castillo'),
	 ('Ortega-Cunningham'),
	 ('Li Inc'),
	 ('Jackson, Harris and Wang'),
	 ('Anderson-Bernard'),
	 ('Bailey, Patton and Moore'),
	 ('Brown, Lewis and Miller'),
	 ('Roy, Martin and King'),
	 ('Russell-Farrell'),
	 ('Baker, Walters and Jensen'),
	 ('Cunningham, Stone and Riddle'),
	 ('Garcia-Santana'),
	 ('Lucas-Bond'),
	 ('Brown-Flores'),
	 ('Cowan-Holloway'),
	 ('Santos, Gonzalez and Holland'),
	 ('Johnson-Shaffer'),
	 ('Montoya, Preston and Garcia'),
	 ('Miles-Kane'),
	 ('Miller-Richards'),
	 ('Barnes and Sons'),
	 ('Thomas-Mcclure'),
	 ('Jensen and Sons'),
	 ('Henry-Hall'),
	 ('Frye Group'),
	 ('Morse-Johnson'),
	 ('Cortez, Lyons and Hill'),
	 ('Owen LLC'),
	 ('Goodwin, Williams and Pittman'),
	 ('Hopkins, Gomez and Little'),
	 ('Johnson-Moore'),
	 ('Chan LLC'),
	 ('Richardson Ltd'),
	 ('Morales Ltd'),
	 ('Anderson Ltd'),
	 ('Hall, Henderson and Bush'),
	 ('Vega-Tate'),
	 ('Ryan, Moore and Thomas'),
	 ('Evans Ltd'),
	 ('Howell, Parks and Hill'),
	 ('Holder-Nolan'),
	 ('Ware-Brown'),
	 ('Castro, Martin and Gibbs'),
	 ('Houston-Thompson'),
	 ('Contreras PLC'),
	 ('Howard-Sandoval'),
	 ('Nelson PLC'),
	 ('Stephens-Hoover'),
	 ('Day-Dominguez'),
	 ('Bradley-Hernandez'),
	 ('Powell, Cohen and Hamilton'),
	 ('Adams-Wallace'),
	 ('Mercado-Henry'),
	 ('Martinez-Villa'),
	 ('Hull Group'),
	 ('Neal, Branch and Fitzpatrick'),
	 ('Bradley-Evans'),
	 ('Allison-Diaz'),
	 ('Washington-Gonzales'),
	 ('Snyder-West'),
	 ('Haynes and Sons'),
	 ('Carter, Wood and Cox'),
	 ('Peters Ltd'),
	 ('Clark-Taylor'),
	 ('Sanchez-Wilson'),
	 ('Edwards-Hurst'),
	 ('Mitchell and Sons'),
	 ('Rollins-Park'),
	 ('Brown and Sons'),
	 ('Todd-Meyer'),
	 ('Harvey-Anderson'),
	 ('Peterson-Clarke'),
	 ('Stephenson, Mitchell and Romero'),
	 ('Norris, Davis and Wilson'),
	 ('Oliver-Mathews'),
	 ('Mitchell-Daniels'),
	 ('Johnson, Benson and Watts'),
	 ('Nguyen Group'),
	 ('Fuentes Group'),
	 ('Luna-Weaver'),
	 ('Finley-Lopez'),
	 ('Anderson, Phillips and Evans'),
	 ('Mckenzie, Henry and Carter'),
	 ('Watson, Dawson and Brown'),
	 ('Thomas Group'),
	 ('Chavez-Davenport'),
	 ('Mcbride-Williams'),
	 ('Hall-Perez'),
	 ('Lee-Singh'),
	 ('Hays LLC'),
	 ('Martinez-Payne'),
	 ('Nelson Ltd'),
	 ('Levy Group'),
	 ('Long PLC'),
	 ('Luna LLC'),
	 ('Kramer LLC'),
	 ('Palmer, Adams and Hill'),
	 ('Wilkins LLC'),
	 ('Larson, Curtis and Hernandez'),
	 ('Dominguez-Cooke'),
	 ('Mendez, Jordan and Coleman'),
	 ('Riddle and Sons'),
	 ('Sampson Group'),
	 ('Pope-Bullock'),
	 ('Escobar and Sons'),
	 ('Clayton PLC'),
	 ('Ashley, Bolton and Kelley'),
	 ('Gutierrez-Yang'),
	 ('Black, Alvarado and Wright'),
	 ('Jennings, Moss and Mason'),
	 ('Holmes, Alexander and Adams'),
	 ('Fritz-Norman'),
	 ('Ross LLC'),
	 ('Anderson Inc'),
	 ('Thomas Inc'),
	 ('Smith-Holland'),
	 ('Frye, Le and Rodriguez'),
	 ('Beck, Stevens and Gilmore'),
	 ('Estrada Ltd'),
	 ('Blanchard-Christensen'),
	 ('Zamora Group'),
	 ('Page Ltd'),
	 ('Pollard Group'),
	 ('Ross, Patterson and Johnson'),
	 ('Horne-Williams'),
	 ('Cannon, West and Hill'),
	 ('Collins-Calhoun'),
	 ('Reyes PLC'),
	 ('Frederick PLC'),
	 ('Rowe LLC'),
	 ('Castro Ltd'),
	 ('Cooper-Wilson'),
	 ('Johnston and Sons'),
	 ('Benson Inc'),
	 ('Daniels and Sons'),
	 ('Griffin-Nelson'),
	 ('Mathis Ltd'),
	 ('Gilbert, Romero and Powell'),
	 ('Hill-Serrano'),
	 ('Diaz, Knapp and Delacruz'),
	 ('Day-King'),
	 ('Schwartz-Choi'),
	 ('Strickland-Allen'),
	 ('Jordan, Daniels and Evans'),
	 ('Ferguson-Scott'),
	 ('Lee-Lee'),
	 ('Skinner, Thompson and Kirk'),
	 ('Armstrong-Clark'),
	 ('Phillips, Johnson and Holmes'),
	 ('Rodriguez and Sons'),
	 ('Miller-Lee'),
	 ('Willis and Sons'),
	 ('Adams-Jackson'),
	 ('Anderson-Thomas'),
	 ('Hart Ltd'),
	 ('Johnson, Harris and Waters'),
	 ('Warner, Jones and Burke'),
	 ('Brewer, Miller and Peterson'),
	 ('Cohen-Nelson'),
	 ('Bailey Group'),
	 ('Lopez-Holland'),
	 ('Smith-Hernandez'),
	 ('Adams-Miller'),
	 ('Curtis Ltd'),
	 ('Arroyo, Anderson and Greer'),
	 ('Jones-Robinson'),
	 ('Andrews-Cox'),
	 ('Bell PLC'),
	 ('Buchanan, Leblanc and Lee'),
	 ('Ross, Wagner and Pollard'),
	 ('Harris-Cabrera'),
	 ('Orr Ltd'),
	 ('Gray-Hoffman'),
	 ('Saunders and Sons'),
	 ('Alexander, Barnes and Boyd'),
	 ('Page-Washington'),
	 ('Graham Inc'),
	 ('Allen Group'),
	 ('Sullivan LLC'),
	 ('Ford-Castro'),
	 ('Robinson Ltd'),
	 ('Holt-Sanchez'),
	 ('Hernandez, Bell and Hogan'),
	 ('Burns-Hogan'),
	 ('Roth-Williams'),
	 ('Cook PLC'),
	 ('Hurst, Vaughan and Howe'),
	 ('Johnson, Edwards and Bennett'),
	 ('Harris, Jones and Alvarez'),
	 ('Morris PLC'),
	 ('Miller, Jones and Myers'),
	 ('Rosario-Fuller'),
	 ('Smith-White'),
	 ('Roberts, Moon and Young'),
	 ('Huffman, Washington and Nelson'),
	 ('Santana-Murillo'),
	 ('Neal, Johnson and Kelly'),
	 ('Nelson-Silva'),
	 ('Dickerson Ltd'),
	 ('Keller LLC'),
	 ('Ramsey PLC'),
	 ('Mitchell, Clark and Mack'),
	 ('Davis and Sons'),
	 ('Andrews Inc'),
	 ('Mendez, Poole and Nelson'),
	 ('Campbell-Rodriguez'),
	 ('Parker, Lee and Chan'),
	 ('Black-Li'),
	 ('Benjamin Group'),
	 ('Ashley, Figueroa and Cruz'),
	 ('Wood, Knight and Boyer'),
	 ('Smith Group'),
	 ('Glover LLC'),
	 ('Cox-Coleman'),
	 ('Mendez PLC'),
	 ('Santana-Allen'),
	 ('Figueroa Group'),
	 ('Vazquez Inc'),
	 ('Bates-Dunn'),
	 ('David-Herrera'),
	 ('Pittman-Moore'),
	 ('Williams-Wright'),
	 ('Miller Inc'),
	 ('Watkins-Baker'),
	 ('Ross, Barrera and Ayala'),
	 ('Le-Davis'),
	 ('Lynch-Robinson'),
	 ('Tucker-Wong'),
	 ('Smith Group'),
	 ('Banks LLC'),
	 ('Navarro Group'),
	 ('Marshall, Cohen and Perez'),
	 ('Kim-Mcdaniel'),
	 ('Keller-Weeks'),
	 ('Rice, Martinez and Stephens'),
	 ('Edwards-Johnson'),
	 ('Knight-Ward'),
	 ('Sanchez-Cannon'),
	 ('Clay-Dunn'),
	 ('Smith Group'),
	 ('Taylor Group'),
	 ('Joseph PLC'),
	 ('Glover-Robertson'),
	 ('Daniel-Cox'),
	 ('Tanner-Bennett'),
	 ('Johns-Washington'),
	 ('Wolf-Cole'),
	 ('Hill, Simpson and Mckinney');
