INSERT INTO Competition (Name)
VALUES	 ('Sparks, Castro and Welch'),
	 ('Fox, Bradley and Wood'),
	 ('Macias, Baird and Walker'),
	 ('Flowers PLC'),
	 ('Roberts-Jackson'),
	 ('Meyer, Fischer and Moore'),
	 ('White PLC'),
	 ('Clark, Johnson and Thompson'),
	 ('Jones Ltd'),
	 ('Garza, Randall and Hayden'),
	 ('Vasquez-Schwartz'),
	 ('Ray Ltd'),
	 ('West and Sons'),
	 ('Lopez and Sons'),
	 ('Nunez Group'),
	 ('Clarke-Reed'),
	 ('Ryan-Griffith'),
	 ('Camacho, Smith and Sutton'),
	 ('Gibson and Sons'),
	 ('Roberts Group'),
	 ('Wilson Inc'),
	 ('Benton, Ramos and Scott'),
	 ('Hill-Meyer'),
	 ('Petty, Smith and Oconnor'),
	 ('Holloway Inc'),
	 ('Gould LLC'),
	 ('Miller-Turner'),
	 ('Swanson PLC'),
	 ('Espinoza Group'),
	 ('Ali-Anderson'),
	 ('Bates, Long and Moon'),
	 ('Clark, Harris and Armstrong'),
	 ('Williams Group'),
	 ('Scott, Williams and Hanna'),
	 ('Hansen-Lindsey'),
	 ('Rogers, King and Jones'),
	 ('Williams, Brock and Brown'),
	 ('Foster, Meyer and Adams'),
	 ('Mack LLC'),
	 ('Black, Johnson and Zavala'),
	 ('Mcdonald Inc'),
	 ('Jenkins-Butler'),
	 ('Thompson and Sons'),
	 ('Johnson-Gill'),
	 ('Williams, Lester and Stanley'),
	 ('Mckinney and Sons'),
	 ('Garcia, Valenzuela and Jordan'),
	 ('Thomas PLC'),
	 ('Parsons-Stephenson'),
	 ('Harris Inc'),
	 ('Jones LLC'),
	 ('Hall, Hall and Wilcox'),
	 ('Smith-Olsen'),
	 ('Patrick, Myers and Brady'),
	 ('Thompson Group'),
	 ('Green LLC'),
	 ('Miller-Lyons'),
	 ('Hernandez-Davis'),
	 ('Shelton, Reid and Cook'),
	 ('Hill-Green'),
	 ('Chapman, Baker and Mason'),
	 ('Jackson, Sharp and Collins'),
	 ('Allen Ltd'),
	 ('Wilson, Smith and Garcia'),
	 ('Hodges PLC'),
	 ('Adams-Clark'),
	 ('Jones Group'),
	 ('Jones, Rodgers and Brown'),
	 ('White, Barnes and Mcconnell'),
	 ('Fuentes PLC'),
	 ('Rodriguez-Buchanan'),
	 ('Fischer-Porter'),
	 ('Dunn, Cochran and Gordon'),
	 ('Newman LLC'),
	 ('Smith-Rios'),
	 ('Boone, Martin and Dean'),
	 ('Dunn-Brown'),
	 ('Anderson PLC'),
	 ('Reid PLC'),
	 ('Owen-Mccarty'),
	 ('White Group'),
	 ('Gross, Hill and Owens'),
	 ('Gill, Williams and Flores'),
	 ('Rhodes-Torres'),
	 ('Smith PLC'),
	 ('Guzman-Jones'),
	 ('Short, Boone and Hansen'),
	 ('James-Sharp'),
	 ('Bolton Inc'),
	 ('Wright-Thomas'),
	 ('Smith-Smith'),
	 ('Dawson-Myers'),
	 ('Morris, Ayala and Smith'),
	 ('Ingram LLC'),
	 ('Murray, Gonzalez and Butler'),
	 ('David PLC'),
	 ('Smith-Crane'),
	 ('Armstrong Inc'),
	 ('Hartman-Miller'),
	 ('Hunter Ltd'),
	 ('Murphy Inc'),
	 ('Hughes, Burch and Baker'),
	 ('Brown-Jones'),
	 ('Hopkins PLC'),
	 ('Mcbride LLC'),
	 ('Jones and Sons'),
	 ('Valencia and Sons'),
	 ('Gonzalez-Bass'),
	 ('Odonnell, Moore and Lamb'),
	 ('Bartlett-Campbell'),
	 ('Hawkins, Adkins and Smith'),
	 ('Reynolds PLC'),
	 ('Bennett-Morales'),
	 ('Ballard-Roth'),
	 ('Howard, Hughes and Lowery'),
	 ('Anderson-Shelton'),
	 ('Hall-Waters'),
	 ('Roberson PLC'),
	 ('Crawford, Garcia and Logan'),
	 ('Steele-Finley'),
	 ('Lopez, Baxter and Gonzalez'),
	 ('Sanchez LLC'),
	 ('Reynolds Group'),
	 ('Villarreal, Miles and Owens'),
	 ('Williams Inc'),
	 ('Vega-Vaughn'),
	 ('Nelson, Warren and Kelly'),
	 ('Anderson PLC'),
	 ('Williams, Moore and Rodriguez'),
	 ('Reeves-Cain'),
	 ('Roberts, Jennings and Ruiz'),
	 ('Christensen, Rivas and Anderson'),
	 ('Young-Figueroa'),
	 ('Hughes, Watkins and Bailey'),
	 ('Tate Inc'),
	 ('Moreno Inc'),
	 ('Brown Ltd'),
	 ('Gross Inc'),
	 ('Stone-Moore'),
	 ('Moss, Bryant and Hernandez'),
	 ('Lang PLC'),
	 ('Donovan-Martinez'),
	 ('Wilson-Lee'),
	 ('Lyons-Morgan'),
	 ('Booker-Jordan'),
	 ('Hall Inc'),
	 ('Pace-Alvarez'),
	 ('Hensley Group'),
	 ('Edwards-Park'),
	 ('Clayton-Pacheco'),
	 ('Conner Inc'),
	 ('Wilson Inc'),
	 ('Phillips-Howard'),
	 ('Golden Ltd'),
	 ('Peterson, Williams and Jenkins'),
	 ('Garcia, Gates and Peterson'),
	 ('Diaz Group'),
	 ('Smith and Sons'),
	 ('Lopez-Fleming'),
	 ('Reyes-Holloway'),
	 ('Sullivan Group'),
	 ('Wright, Harrell and Bautista'),
	 ('Gardner PLC'),
	 ('Barber, Sullivan and Jones'),
	 ('Mcdowell, Young and Luna'),
	 ('Mosley, Hogan and Morgan'),
	 ('Schultz Ltd'),
	 ('Myers, Donaldson and Flores'),
	 ('Buck, George and Brown'),
	 ('Hunt, Scott and Warner'),
	 ('Richards-Flores'),
	 ('Joseph, Smith and Haynes'),
	 ('Miller and Sons'),
	 ('Cooper Inc'),
	 ('Hernandez, Miller and Watson'),
	 ('Wilson, Miller and Williams'),
	 ('Herrera, Booth and Gilmore'),
	 ('Davis-Mckenzie'),
	 ('Miller-Hart'),
	 ('Ramirez Group'),
	 ('Dawson PLC'),
	 ('Johnson-Moore'),
	 ('Gill, Cook and Jackson'),
	 ('Henderson-Thomas'),
	 ('Craig-Young'),
	 ('Garcia Group'),
	 ('Hall-Parker'),
	 ('Brown, Gilbert and Miller'),
	 ('Wilson-Murphy'),
	 ('King-Baird'),
	 ('Nguyen, Morrison and Cruz'),
	 ('Evans, Moore and Lindsey'),
	 ('Foley, Johnson and Franklin'),
	 ('Morgan PLC'),
	 ('Williams, Brooks and Graham'),
	 ('Garcia-Vasquez'),
	 ('Schmidt Group'),
	 ('White and Sons'),
	 ('Porter, Pierce and Calderon'),
	 ('Robinson Ltd'),
	 ('Hoffman Inc'),
	 ('Alexander, Willis and Russo'),
	 ('Atkinson-Hernandez'),
	 ('Giles, Leonard and Dunn'),
	 ('Edwards-Black'),
	 ('Bowman, Williams and Leblanc'),
	 ('Meadows-Carlson'),
	 ('Anderson and Sons'),
	 ('Carr Ltd'),
	 ('Diaz-Duncan'),
	 ('Jones, Sanchez and Wallace'),
	 ('Perry-Gibbs'),
	 ('Simmons LLC'),
	 ('Hogan, Cox and Schmidt'),
	 ('Henry-Hanna'),
	 ('Mcguire Inc'),
	 ('Mcdaniel-Scott'),
	 ('Foster, Bell and Cox'),
	 ('Bates LLC'),
	 ('Moreno, Grant and Mccormick'),
	 ('Hull LLC'),
	 ('Montgomery-Smith'),
	 ('Gaines PLC'),
	 ('Rollins-Robinson'),
	 ('Bauer Group'),
	 ('Sampson, Hall and Beck'),
	 ('Freeman Group'),
	 ('Wang LLC'),
	 ('Salas-Rogers'),
	 ('Carlson-Clark'),
	 ('Ramirez, Green and Quinn'),
	 ('Boyer-Johnson'),
	 ('Rubio-Rodriguez'),
	 ('Cordova, Parker and Jackson'),
	 ('Kennedy-Townsend'),
	 ('Horn, Gibson and Campbell'),
	 ('Anderson, Anderson and Campbell'),
	 ('Arnold-Cardenas'),
	 ('Scott, Mercado and Mendoza'),
	 ('Johnson-Reeves'),
	 ('Ferrell-Day'),
	 ('Miller Inc'),
	 ('Barnes Group'),
	 ('King Group'),
	 ('Arias Inc'),
	 ('Yang-Warren'),
	 ('Taylor-Jensen'),
	 ('Walker Inc'),
	 ('Nichols-Lawson'),
	 ('Cooley, Powers and Lloyd'),
	 ('Walker-Vazquez'),
	 ('Phillips, Holloway and Chaney'),
	 ('Jenkins, Becker and Pacheco'),
	 ('Peterson, Jackson and Hawkins'),
	 ('Allen, Baldwin and Calderon'),
	 ('Bush, West and Chapman'),
	 ('Wright Ltd'),
	 ('Bridges-Barnett'),
	 ('Powell Group'),
	 ('Johnson, Greene and Hebert'),
	 ('Stevenson, Odom and Reyes'),
	 ('Gonzalez and Sons'),
	 ('Spencer, Powers and Rush'),
	 ('Allen Group'),
	 ('Martinez, Lynch and Harris'),
	 ('Ross, Hernandez and Thompson'),
	 ('Hardy, Boyd and Jenkins'),
	 ('Faulkner-Cruz'),
	 ('Moore, Marshall and Williams'),
	 ('Wilson Inc'),
	 ('Wilson, Roth and Bruce'),
	 ('Boyer Inc'),
	 ('Gonzalez-Mcgee'),
	 ('Valencia PLC'),
	 ('Hendrix-Campbell'),
	 ('Morrison Group'),
	 ('Pierce, Smith and Thompson'),
	 ('Jackson, Wood and Stout'),
	 ('Jones Group'),
	 ('Perry-Black'),
	 ('Gray Inc'),
	 ('Dillon and Sons'),
	 ('Jenkins Inc'),
	 ('Stevens, Watson and Morgan'),
	 ('Wilson, Carter and Campbell'),
	 ('Horton-Dawson'),
	 ('Wright-Soto'),
	 ('Baker, Wilson and Howell'),
	 ('Holland, Thompson and Cowan'),
	 ('Salinas, Brewer and Mahoney'),
	 ('Myers-Lawrence'),
	 ('Peterson, Hart and Lewis'),
	 ('Moss LLC'),
	 ('Dunn, Shaffer and Schmitt'),
	 ('Ferguson, Price and Rangel'),
	 ('Alvarez-Davis'),
	 ('Summers, Casey and Ellis'),
	 ('Ryan and Sons'),
	 ('Walsh, Ryan and Schaefer'),
	 ('Clark Ltd'),
	 ('Huffman, Williams and Knox'),
	 ('Drake-Wong'),
	 ('Thompson, Zimmerman and Coffey'),
	 ('Vance Inc'),
	 ('Hickman, Rice and Grant'),
	 ('Bailey, Obrien and Mccarty'),
	 ('Hudson, White and Mcdowell'),
	 ('Williams-White'),
	 ('Beck-Conley'),
	 ('Garcia-Andrews'),
	 ('Taylor, Lopez and Abbott'),
	 ('Mcpherson Group'),
	 ('Turner-Petersen'),
	 ('Mcconnell-Pollard'),
	 ('Huerta-Wilson'),
	 ('Perkins Group'),
	 ('Young, Bryant and Scott'),
	 ('Mitchell, Thomas and Johnson'),
	 ('Hunt LLC'),
	 ('Porter Group'),
	 ('Wilson, Flores and Newton'),
	 ('Williams-Collier'),
	 ('Cross-Stanley'),
	 ('Haney-Campbell'),
	 ('Collins Ltd'),
	 ('Wilson-Schmidt'),
	 ('Crawford-Flores'),
	 ('Nelson, Chapman and Cole'),
	 ('Taylor Inc'),
	 ('Torres-Smith'),
	 ('Sharp LLC'),
	 ('Bennett, Klein and Hunter'),
	 ('Nguyen, Patterson and Moore'),
	 ('Wilson-Davis'),
	 ('Phillips, Mason and Mendez'),
	 ('English, Powers and Gilmore'),
	 ('Collins and Sons'),
	 ('Parker Ltd'),
	 ('Duran, Anderson and Le'),
	 ('Thomas Ltd'),
	 ('Ward LLC'),
	 ('Morrison Inc'),
	 ('White Inc'),
	 ('Adams LLC'),
	 ('Harris LLC'),
	 ('Phillips and Sons'),
	 ('Sanchez and Sons'),
	 ('Mcintosh LLC'),
	 ('Johnson-Hess'),
	 ('Franklin-Price'),
	 ('Harris Group'),
	 ('Malone, Hunter and West'),
	 ('Wang and Sons'),
	 ('Anderson-Perez'),
	 ('Moore Inc'),
	 ('Burch, Pratt and Perez'),
	 ('Perez-Mccarthy'),
	 ('Larsen-Pierce'),
	 ('Whitehead LLC'),
	 ('Perez-Patterson'),
	 ('Thompson-Grant'),
	 ('Wagner-Dean'),
	 ('Meza-Boone'),
	 ('Davidson Inc'),
	 ('Butler, Winters and Boyd'),
	 ('Ponce and Sons'),
	 ('Carter-Dougherty'),
	 ('Huber, Castaneda and King'),
	 ('Johnson, Paul and Lindsey'),
	 ('Thompson LLC'),
	 ('Johnson, Morales and Perez'),
	 ('Norman, Hoover and Adams'),
	 ('Bates Ltd'),
	 ('Jones, Evans and Davis'),
	 ('Hicks, Rodriguez and Larsen'),
	 ('Rodriguez Inc'),
	 ('Hernandez Inc'),
	 ('Butler, Reyes and Cunningham'),
	 ('Munoz-Castro'),
	 ('Atkinson Inc'),
	 ('Valentine, Ramos and Small'),
	 ('Dawson, Aguirre and Rojas'),
	 ('Stanton and Sons'),
	 ('Bennett PLC'),
	 ('Johnson, Watson and Rivera'),
	 ('Smith and Sons'),
	 ('Garcia-Walter'),
	 ('Griffin, Smith and Jones'),
	 ('Brandt, Little and Williams'),
	 ('Jones, Tucker and Lee'),
	 ('Hawkins, Barton and Young'),
	 ('Saunders, Richard and Wiggins'),
	 ('Durham Ltd'),
	 ('Ford Inc'),
	 ('Gonzalez, Wiggins and Shaw'),
	 ('Robinson, Miller and Hill'),
	 ('Davis-Pope'),
	 ('Hill Inc'),
	 ('Parsons-Schultz'),
	 ('West and Sons'),
	 ('Larson-Riley'),
	 ('Taylor and Sons'),
	 ('Dixon, Wright and Manning'),
	 ('Morgan-Smith'),
	 ('Thompson, Lawrence and Snow'),
	 ('Smith, Hinton and Sweeney'),
	 ('Becker Group'),
	 ('Garcia-Horn'),
	 ('Jackson and Sons'),
	 ('Watson-Robertson'),
	 ('Bennett, Jackson and Martinez'),
	 ('Huff LLC'),
	 ('Griffith, Tran and Hunter'),
	 ('Hicks and Sons'),
	 ('Parker-Contreras'),
	 ('Mcdonald-Gay'),
	 ('Kelly Group'),
	 ('Sandoval-Carr'),
	 ('Miller, Dunn and Reyes'),
	 ('Owens, Torres and Wilson'),
	 ('Small PLC'),
	 ('Evans, Liu and Rodriguez'),
	 ('Williams-Walker'),
	 ('Roberts, Pratt and Walker'),
	 ('Green, Whitaker and Koch'),
	 ('Brown LLC'),
	 ('Nichols-Sawyer'),
	 ('Hughes Group'),
	 ('Pearson LLC'),
	 ('Martinez, Obrien and Payne'),
	 ('Wilkinson and Sons'),
	 ('French, Nguyen and Conrad'),
	 ('Hanson, Day and Nelson'),
	 ('Leonard Ltd'),
	 ('Davis, Daniel and Daniel'),
	 ('King and Sons'),
	 ('Meyers-Miller'),
	 ('Jones-West'),
	 ('Stevens, Weber and Howard'),
	 ('Hughes PLC'),
	 ('Velasquez-Tucker'),
	 ('Adkins, James and Brown'),
	 ('Hopkins, Griffin and Wang'),
	 ('Martinez-Garrett'),
	 ('Garrison-Knox'),
	 ('Johnson PLC'),
	 ('Hensley and Sons'),
	 ('Rojas and Sons'),
	 ('Henry LLC'),
	 ('Guerrero, Wright and Nelson'),
	 ('Roberts-Smith'),
	 ('Franklin Inc'),
	 ('Nunez-Green'),
	 ('Perry, Davenport and Boyle'),
	 ('Garcia, Kramer and Thomas'),
	 ('Davis-Terrell'),
	 ('Brown-Williams'),
	 ('Graham, Hampton and Ryan'),
	 ('Stafford, Bolton and Parker'),
	 ('Brown Ltd'),
	 ('Shepard, Boyd and Owens'),
	 ('Smith-Moore'),
	 ('Flores Ltd'),
	 ('Graham, Gonzalez and Stevens'),
	 ('Adkins, Evans and Carroll'),
	 ('Spencer, Haynes and Johnson'),
	 ('Davenport, Mccoy and Newton'),
	 ('Campbell, Martin and James'),
	 ('Barr-Rodriguez'),
	 ('Combs, Jackson and Avila'),
	 ('Duncan, Patton and Proctor'),
	 ('Barnes, Reed and Jones'),
	 ('Patterson-Johnson'),
	 ('Buck, Lopez and Morris'),
	 ('Villa Ltd'),
	 ('Nichols-Dixon'),
	 ('Cain and Sons'),
	 ('Porter, Alvarez and Morales'),
	 ('Carter, Pineda and Villegas'),
	 ('Martinez, Payne and Johnson'),
	 ('Hall Ltd'),
	 ('Hardy, Stewart and Walker'),
	 ('Torres, Koch and Robinson'),
	 ('Lewis and Sons'),
	 ('Johnson-Lane'),
	 ('Spence-Johnson'),
	 ('Holmes-Thompson'),
	 ('Yates-Morris'),
	 ('Diaz-Welch'),
	 ('Cochran, Wolf and Cortez'),
	 ('Powell-Johnson'),
	 ('Li-Hines'),
	 ('Carlson-Mejia'),
	 ('Parks and Sons'),
	 ('Curry, Morales and Mejia'),
	 ('Richmond-Neal'),
	 ('Lewis and Sons'),
	 ('Strong-Simon'),
	 ('Henderson Inc'),
	 ('Flowers, Brewer and Murphy');
